# Generated by Django 3.1.7 on 2021-03-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance_System_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leavereportstudents',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leavereportteachers',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
